name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths-ignore:
    - "README.md"
    
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-publish-as-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    # if: startsWith(github.ref, 'refs/heads/master') # Running this job only for master

    steps:
      - uses: actions/checkout@v3
    
      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: test
          labels: test

      - name: Build and publish Docker Image to GitHub Packages Registry
        # You may pin to the exact commit or the version.
        # uses: VaultVulp/gp-docker-action@abd86dfdcd23929f6195a0fd455769a73b7276da
        uses: VaultVulp/gp-docker-action@1.2.0
        with:
          # GitHub token to push Docker image to GitHub Packages
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # Docker Image name
          image-name: kubectl-helm-runner
          image-tag: test
          # build-context: /docker
          dockerfile: Dockerfile
