name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths-ignore:
    - "README.md"

jobs:
  build-and-publish-as-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2

    - name: Build and publish Docker Image to GitHub Packages Registry
      uses: VaultVulp/gp-docker-action@1.2.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        image-name: kubectl-helm-runner
        image-tag: test
        dockerfile: Dockerfile
